### ISSUE TITLE
Application to other platform(s) as well?

### ISSUE THREAD

**Issue by ghost** [RoyalFlyBy/ChaturbateDownloader#3]
Good morning, **@RoyalFlyBy**: hope everything goes well; anyway better than _here_, in my Homeland😷. 

I'd an idea, but I don't know if it's possible to do: considering how Your application works, couldn't its use be extended to other similar platforms where models perform, making only a few changes? An example is [xHamsterLive](https://xhamsterlive.com/): it's **roughly same** as Chaturbate in the operating mechanisms: You notice that model has opened the Room in Your mailbox, You paid tokens, there're public and private sessions, etc.

Based on Your experience, is it a feasible suggestion🤔?

**Comment by RoyalFlyBy** [comment]
Hi, doing alright for now, what about you?

Yea I was thinking about this that's why I have started building a new application with a modular plugin system. So I could standardize and make adding sites a lot easier, in which case it would be feasible.

However in it's current form it wouldn't be that feasible, but yea once I finalize that other application I can definitely add this to a list of supported sites.

**Comment by ghost** [comment]
Thanks, I too haven't contracted Corona _for now_ and I try to remain as positive as possible.

BTW, the new application sounds great😲.
I wanted to ask for a detail: will the new app have also **ChaturbateWatcher** functionality (download streams of models I subscribe to with a sort of auto-recording via notifications in dedicated mailbox) ?

**Comment by RoyalFlyBy** [comment]
Yes I would probably try and make it notification compatible like cbWatcher, in a similar fashion too via email notifications

Although more and more services are beginning to phase out email notifications and are moving to browser push notifications instead (like cb, their email notification system is unreliable but their push notification system seems to be more accurate)
At the moment most my efforts in this field are halted until I find a way to implement push notification support

**Comment by RoyalFlyBy** [comment]
For anyone wondering about the status in this, I actually did figure out how to listen for push notifications but haven't fully figured out how to subscribe to them for websites. Getting close though
